name: Test

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-sdk-file: commandlinetools-linux-9477386_latest.zip  # Use the latest version

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install system image and create AVD
        run: |
          echo "Installing system image..."
          yes | sdkmanager --install "system-images;android-35;default;x86_64"
          echo "Creating AVD..."
          echo "no" | avdmanager create avd -n test -k "system-images;android-35;default;x86_64" -d "Nexus 6"
          echo "Configuring AVD..."
          mkdir -p /home/runner/.android/avd/test.avd
          echo "hw.ramSize=4096" >> /home/runner/.android/avd/test.avd/config.ini
          echo "disk.dataPartition.size=2G" >> /home/runner/.android/avd/test.avd/config.ini
          echo "hw.gpu.mode=host" >> /home/runner/.android/avd/test.avd/config.ini
          echo "hw.keyboard=yes" >> /home/runner/.android/avd/test.avd/config.ini
          echo "hw.camera.back=none" >> /home/runner/.android/avd/test.avd/config.ini
          echo "hw.camera.front=none" >> /home/runner/.android/avd/test.avd/config.ini
          echo "vm.heapSize=256" >> /home/runner/.android/avd/test.avd/config.ini
          cat /home/runner/.android/avd/test.avd/config.ini

      - name: Run tests with Android Emulator
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          arch: x86_64
          api-level: 35  # Android API level 35
          profile: Nexus 6  # Optional: Specify a device profile
          disable-animations: true  # Disable animations for faster tests
          emulator-options: -no-audio -no-boot-anim -no-snapshot -no-window -gpu host  # Use host GPU for better rendering
          script: ./gradlew connectedCheck  # Run all connected tests

      - name: Archive code coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/androidTests/
          retention-days: 7